// <auto-generated />
using System;
using BudgetIT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BudgetIT.Migrations
{
    [DbContext(typeof(BudgetITContext))]
    [Migration("20210410222533_Update04")]
    partial class Update04
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BudgetIT.Models.BudgetRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FornecedorId");

                    b.Property<int?>("NotaFiscalProdutoId");

                    b.Property<int?>("NotaFiscalServicoId");

                    b.Property<int?>("ServicoId");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("NotaFiscalProdutoId");

                    b.HasIndex("NotaFiscalServicoId");

                    b.HasIndex("ServicoId");

                    b.ToTable("BudgetRecord");
                });

            modelBuilder.Entity("BudgetIT.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro");

                    b.Property<string>("CEP");

                    b.Property<string>("CNPJ");

                    b.Property<string>("Filial");

                    b.Property<string>("InscEstatudal");

                    b.Property<string>("InscMunicipal");

                    b.Property<string>("Logradouro");

                    b.Property<string>("NomeFantasia");

                    b.Property<string>("RazaoSocial");

                    b.Property<string>("Telefone");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 1)));

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("BudgetIT.Models.ClienteFornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ClienteId");

                    b.Property<int>("FornecedorId");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FornecedorId");

                    b.ToTable("ClienteFornecedor");
                });

            modelBuilder.Entity("BudgetIT.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CEP");

                    b.Property<string>("CNPJ");

                    b.Property<string>("InscEstatudal");

                    b.Property<string>("InscMunicipal");

                    b.Property<string>("Logradouro");

                    b.Property<string>("Municipio");

                    b.Property<string>("NomeFantasia");

                    b.Property<string>("RazaoSocial");

                    b.Property<string>("Telefone");

                    b.Property<string>("UF");

                    b.HasKey("Id");

                    b.ToTable("Fornecedor");
                });

            modelBuilder.Entity("BudgetIT.Models.NotaFiscalProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Emissao");

                    b.Property<int>("FornecedorId");

                    b.Property<string>("NrNota");

                    b.Property<string>("Oc");

                    b.Property<int>("Status");

                    b.Property<double>("Valor");

                    b.Property<DateTime>("Vencimento");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("NotaFiscalProduto");
                });

            modelBuilder.Entity("BudgetIT.Models.NotaFiscalServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Emissao");

                    b.Property<int>("FornecedorId");

                    b.Property<string>("NrNota");

                    b.Property<string>("Oc");

                    b.Property<int>("Status");

                    b.Property<double>("Valor");

                    b.Property<DateTime>("Vencimento");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("NotaFiscalServico");
                });

            modelBuilder.Entity("BudgetIT.Models.Servico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao");

                    b.Property<int>("FornecedorId");

                    b.Property<string>("Tipo");

                    b.HasKey("Id");

                    b.HasIndex("FornecedorId");

                    b.ToTable("Servico");
                });

            modelBuilder.Entity("BudgetIT.Models.BudgetRecord", b =>
                {
                    b.HasOne("BudgetIT.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId");

                    b.HasOne("BudgetIT.Models.NotaFiscalProduto", "NotaFiscalProduto")
                        .WithMany()
                        .HasForeignKey("NotaFiscalProdutoId");

                    b.HasOne("BudgetIT.Models.NotaFiscalServico", "NotaFiscalServico")
                        .WithMany()
                        .HasForeignKey("NotaFiscalServicoId");

                    b.HasOne("BudgetIT.Models.Servico", "Servico")
                        .WithMany()
                        .HasForeignKey("ServicoId");
                });

            modelBuilder.Entity("BudgetIT.Models.ClienteFornecedor", b =>
                {
                    b.HasOne("BudgetIT.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BudgetIT.Models.Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BudgetIT.Models.NotaFiscalProduto", b =>
                {
                    b.HasOne("BudgetIT.Models.Fornecedor", "Fornecedor")
                        .WithMany("provider1")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BudgetIT.Models.NotaFiscalServico", b =>
                {
                    b.HasOne("BudgetIT.Models.Fornecedor", "Fornecedor")
                        .WithMany("provider2")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BudgetIT.Models.Servico", b =>
                {
                    b.HasOne("BudgetIT.Models.Fornecedor", "Fornecedor")
                        .WithMany("Serv")
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
